DROP DATABASE escuela;

CREATE DATABASE escuela;

USE escuela;

CREATE TABLE ESTUDIANTE(
ID INT NOT NULL, 
NOMBRE VARCHAR (20) NOT NULL, ANO_INGRESO  INT NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE ASIGNATURA(
CODIGO VARCHAR(7) NOT NULL,
NAME VARCHAR (20) NOT NULL,
SEMESTRE INT NOT NULL,       
PRIMARY KEY (CODIGO)
);

CREATE TABLE CURSAR(
ESTUDIANTE_ID INT NOT NULL,
ASIGNATURA_CODIGO VARCHAR(7) NOT NULL,
AÑO INT NOT NULL,
NOTA_FINAL FLOAT NOT NULL,
PRIMARY KEY(ESTUDIANTE_ID, ASIGNATURA_CODIGO, AÑO),
FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ID),
FOREIGN KEY (ASIGNATURA_CODIGO) REFERENCES ASIGNATURA(CODIGO)
);

CREATE TABLE TENER_REQUISITO(
ASIGNATURA_NECESARIA VARCHAR(7) NOT NULL,
ASIGNATURA VARCHAR(7) NOT NULL,
PRIMARY KEY(ASIGNATURA_NECESARIA, ASIGNATURA)
);

ALTER TABLE TENER_REQUISITO ADD CONSTRAINT fk1 FOREIGN KEY (ASIGNATURA_NECESARIA) REFERENCES ASIGNATURA(CODIGO);

ALTER TABLE TENER_REQUISITO ADD CONSTRAINT fk2 FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(CODIGO);
